JuliaBooks/Books.jl

- Project.toml
Release notes:
This release is breaking due to #70. Apart from that, including images is massively more convenient due to #66.
> Set version to 0.3.0

- src/html.jl
- test/html.jl
This will fix the `StringIndexError` when the header contains some non-ASCII characters
Ref: https://docs.julialang.org/en/v1/manual/strings/#Unicode-and-UTF-8
> Fix StringIndexError when extracting section info

- src/generate.jl
- src/serve.jl
This avoids spamming the LiveServer with many changed files in `_gen` and, therefore, improves performance considerably.
> Add call_html at the end of gen

- defaults/config.toml
- docs/Project.toml
- docs/config.toml
- docs/contents/index.md
- docs/src/BooksDocs.jl
- docs/src/includes.jl
- src/build.jl
- src/defaults.jl
- src/generate.jl
Fixes https://github.com/rikhuijzer/Books.jl/issues/72.
This issue got me down a bit of a spiral. The user can now also specify 
```
include_homepage_outside_html = true
```
which will ensure that the homepage contents are added to offline documents like PDF too. 
However, then the question is how to ensure that the homepage is easily accessible for the user. That is, to not only hide it behind the home button, but also show it as a section in the menu. This is opened as a new issue: https://github.com/rikhuijzer/Books.jl/issues/99.
> Also generate content for homepage

- docs/contents/demo.md
- src/html.jl
> Fix note box and long section names

- src/Books.jl
- src/build.jl
- src/generate.jl
- src/html.jl
Thanks to https://github.com/aviatesk/JET.jl.
> Fix some problems found by JET

- docs/config.toml
- docs/contents/demo.md
- docs/src/includes.jl
- src/showcode.jl
- test/showcode.jl
Fixes https://github.com/rikhuijzer/Books.jl/issues/136.
Also, now, you can add a `# hide` comment behind lines in a method definition inside a package.
Then, these lines will not be shown.
> Assume less in @sc and @sco

- src/html.jl
- src/outputs/makie.jl
- test/html.jl
Now, links to png images are only changed to svg if there is an svg image available, which is better in general.
> Fix GLMakie

- docs/contents/demo.md
- src/build.jl
- src/generate.jl
- test/build.jl
- test/generate.jl
Fixes #175. 
The indented code blocks now need to have an empty line before the block.
> Fix indentation

- docs/contents/demo.md
- src/build.jl
- src/generate.jl
- test/build.jl
Code blocks on the third level in lists were evaluated but the output was wrong. Specifically, it was indented too much, causing Pandoc to interpret it incorrectly.
> Fix third level indent

- defaults/style.css
- src/html.jl
In #204, there was a small bug which caused the footnote number in the text to not match the number at the bottom of the page.
> Fix number in footnote list

- docs/contents/demo.md
- src/Books.jl
- src/showcode.jl
- test/showcode.jl
Thanks to the pre keyword, we can wrap options around any object:
```
function my_func()
return DataFrame(; x = [1])
end
```
```jl
pre(out) = Options(out; caption="Caption")
@sco pre=pre my_func()
```
> Add pre keyword to @sco and sco

- src/showcode.jl
- test/showcode.jl
These changes ensure that `@sc` also works when the user did `using Books: foo` instead of `using Books` (with the former, `Books` is undefined in the module).
> Make `@sc` more reliable

- src/Books.jl
- src/build.jl
- src/output.jl
- src/outputs/aog.jl
- src/outputs/makie.jl
- src/outputs/plots.jl
- test/output.jl
- test/runtests.jl
For more info, see <https://jump.dev/JuMP.jl/v0.21/developers/style/#using-vs.-import>.
> Explicitly load symbols

- defaults/template.tex
- docs/contents/about.md
Enables colored links for cross-references etc.
Also, makes the appearance of syntax highlighting in HTML and PDF more consistent.
> Enable colorlinks and improve syntax highlighting

- src/build.jl
Instead of printing the **full** HTML, the error is now simply:
```
julia> html(; fail_on_error=true)
Undefined cross-reference: fig:stats_vs_prob
ERROR: Output contains undefined cross-references:
- fig:stats_vs_prob
Stacktrace:
[1] error(s::String)
@ Base ./error.jl:33
[2] verify_cross_references(h::String)
@ Books ~/git/Books.jl/src/build.jl:170
[3] pandoc_html(project::String; fail_on_error::Bool)
@ Books ~/git/Books.jl/src/build.jl:203
[4] html(; project::String, extra_head::String, fail_on_error::Bool, build_sitemap::Bool)
@ Books ~/git/Books.jl/src/build.jl:268
[5] top-level scope
@ REPL[19]:1
```
> Improve undefined cross-reference error

- src/build.jl
Fixes #248.
The error is now a warning:
```
julia> html()
┌ Warning: _gen doesn't exist. Did you run `gen()`?
└ @ Books ~/git/Books.jl/src/build.jl:166
[...]
```
> Make gen dir if missing

- defaults/template.html
- src/build.jl
- test/build.jl
- test/sitemap.jl
> Add url_prefix for JuliaMono and Mousetrap

- defaults/style.css
- src/html.jl
Some menu entries were not cut off in the Books documentation and Julia Data Science. Setting the menu wider looked ugly, so this reduces the threshold again.
> Reduce menu cutoff threshold

- Artifacts.toml
- src/build.jl
Contains one fix for Julia thanks to Fons (https://github.com/highlightjs/highlight.js/pull/3432) and some small improvements to general colors (https://github.com/highlightjs/highlight.js/releases/tag/11.4.0).
> Switch to Highlight 11.4.0

- defaults/metadata.yml
- defaults/template.tex
Users can set CJKmainfont in metadata.yml to render CJK characters in PDF, but for now the CJKmainfont must be SYSTEM FONTS.
> Add CJK support for PDF in template.tex and metadata.yml
