JuliaBooks/Books.jl

- .github/workflows/CI.yml
- src/Books.jl
- src/ci.jl
> Install dependencies via Julia

- .github/workflows/CI.yml
- docs/chapters/demo.md
- src/ci.jl
- test/generate.jl
> Fix cairosvg installation

- .github/workflows/CI.yml
- defaults/metadata.yml
- src/ci.jl
> Install Source Code Pro font

- docs/contents/about.md
- docs/contents/demo.md
- docs/contents/getting-started.md
- docs/src/includes.jl
- src/Books.jl
- src/generate.jl
- src/output.jl
- src/outputs/compose.jl
- src/outputs/dataframes.jl
- src/outputs/gadfly.jl
> Allow for setting captions and labels

- .github/workflows/CI.yml
- src/ci.jl
> Reduce the number of installed dependencies

- .github/workflows/CI.yml
- .gitignore
- docs/contents/about.md
- docs/contents/demo.md
- docs/contents/getting-started.md
- docs/src/BooksDocs.jl
- docs/src/includes.jl
- src/Books.jl
- src/generate.jl
- src/html.jl
- test/runtests.jl
Also renames the `_generated` directory to `_gen`.
Closes #69.
> Change generate_content to gen

- .github/workflows/CI.yml
- defaults/config.toml
- defaults/template.html
- docs/config.toml
- src/Books.jl
- src/build.jl
- src/defaults.jl
- src/html.jl
- test/html.jl
> Add url_prefix

- docs/contents/demo.md
- docs/src/includes.jl
- src/Books.jl
- src/generate.jl
- src/output.jl
- src/outputs/compose.jl
- src/showcode.jl
- test/generate.jl
- test/showcode.jl
> Allow calling @sc and @sco via path

- defaults/style.css
- defaults/template.html
- src/html.jl
Fixes https://github.com/rikhuijzer/Books.jl/issues/126.
> Place footer at bottom of screen

- src/build.jl
- src/defaults.jl
- src/html.jl
- test/html.jl
> Reduce @report_dispatch possible errors from 76 to 7

- src/generate.jl
> Improve error reporting

- docs/contents/demo.md
- docs/src/includes.jl
- src/generate.jl
- src/showcode.jl
- test/showcode.jl
> Show method call when using @sco

- src/Books.jl
- src/build.jl
Fix #160 (Could not find executable pandoc-crossref).
> Explicitly specify pandoc_crossref_path

- docs/contents/index.md
- src/generate.jl
- src/outputs/dataframes.jl
- test/output.jl
- test/runtests.jl
> Fix underscores in DataFrames

- src/generate.jl
> Handle terminal interrupt better

- src/Books.jl
- src/build.jl
> Omit welcome page from Docx and PDF

- src/Books.jl
- src/build.jl
- src/ci.jl
- src/html.jl
- src/sitemap.jl
- test/html.jl
- test/sitemap.jl
> Omit html suffix in links

- defaults/style.css
- docs/contents/demo.md
- src/html.jl
- test/html.jl
> Fix footnotes showing up at references

- docs/contents/demo.md
- docs/src/includes.jl
- src/output.jl
- src/outputs/aog.jl
- src/outputs/dataframes.jl
- src/outputs/makie.jl
- src/outputs/plots.jl
- test/Project.toml
- test/output.jl
- test/runtests.jl
> Add link_attributes

- docs/contents/demo.md
- docs/src/includes.jl
- src/build.jl
- src/output.jl
- test/build.jl
> Fix inline blocks

- defaults/template.tex
Thanks to https://tectonic-typesetting.github.io/book/latest/getting-started/unicode.html.
> Switch to modern font

- docs/config.toml
- src/build.jl
- src/ci.jl
- src/defaults.jl
- src/sitemap.jl
- test/sitemap.jl
> Add 404.html and robots.txt

- defaults/metadata.yml
- defaults/template.tex
- docs/metadata.yml
- src/build.jl
- Also closes https://github.com/rikhuijzer/Books.jl/issues/59.
> Add frontmatter

- src/build.jl
- src/ci.jl
> Remove Tectonic patch

- src/build.jl
- src/ci.jl
> Replace IS_CI with is_ci()

- docs/contents/demo.md
> Update docs for JuliaMono

- .github/workflows/CI.yml
- defaults/template.tex
- src/build.jl
- src/ci.jl
- test/runtests.jl
This one works unlike #257.
Properly fixes #254.
> Avoid `install_dependencies`

- .github/workflows/CI.yml
- .github/workflows/Docs.yml
I get the `pandoc_crossref` error on MacOS using Apple Silicon.
Maybe running CI on `macos-latest` will also help debug this.
> Run CI on MacOS
